import { Content } from "@/types/content";

export const MOCK_CONTENTS: Content[] = [
  {
    objectid: "1",
    objecttype: "CONTENT",
    partnerid: null,
    title: "Spider-Man: No Way Home",
    defaulttitle: "Spider-Man: No Way Home",
    defaultgenre: "Acción",
    publishtime: "2026-02-06 00:27:22",
    endtime: "2026-06-05 00:00:00",
    shortdescription: "Por primera vez en la historia, se revela la identidad.",
    ratingtype: "NUMERIC",
    pgrating: "+13",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Acción",
    subgenre: ["Aventura"],
    thumbnail: null,
    tags: ["Acción"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Spider-Man adventure.",
    objecttag: null,
    details: null,
    productionyear: 2021,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 8439,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "1",
    contentprovider: "sony",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "1",
      title: "Spider-Man",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/ole/sony-movies/mo-portrait-696e4668b56773fc5dac4f9a-000000.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["SYMBOL1"]
  },
  {
    objectid: "2",
    objecttype: "CONTENT",
    partnerid: null,
    title: "Los Secretos De La Calle Maple",
    defaulttitle: "Los Secretos",
    defaultgenre: "Misterio",
    publishtime: "2026-01-10",
    endtime: "2026-04-30",
    shortdescription: "Misterio en la ciudad.",
    ratingtype: "NUMERIC",
    pgrating: "+18",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Misterio",
    subgenre: [],
    thumbnail: null,
    tags: ["Misterio"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Mystery thriller.",
    objecttag: null,
    details: null,
    productionyear: 2024,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 5181,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "2",
    contentprovider: "lifetime",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "2",
      title: "Secrets",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/ole/lifetime/mo-portrait-68cb6a6ef47a6917752bf34a-810107.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["IC5KD8ZO"]
  },
  {
    objectid: "3",
    objecttype: "CONTENT",
    partnerid: null,
    title: "Mulholland Drive",
    defaulttitle: "Mulholland Drive",
    defaultgenre: "DRAMA",
    publishtime: "2025-12-30",
    endtime: "2026-08-01",
    shortdescription: "Drama en Hollywood.",
    ratingtype: "NUMERIC",
    pgrating: "+18",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "DRAMA",
    subgenre: ["THRILLER"],
    thumbnail: null,
    tags: ["Drama"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Hollywood mystery.",
    objecttag: null,
    details: null,
    productionyear: 2001,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 8852,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "3",
    contentprovider: "CINDIE",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "3",
      title: "Mulholland",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/cindie/mo-dish0000000010680801-dm_20240821_1052_20240821095858-750d569b6c0536e9.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["23VPUSTI"]
  },
  {
    objectid: "4",
    objecttype: "CONTENT",
    partnerid: null,
    title: "As We Speak",
    defaulttitle: "As We Speak",
    defaultgenre: "Musical",
    publishtime: "2026-01-02",
    endtime: "2051-12-31",
    shortdescription: "Documental musical.",
    ratingtype: "NUMERIC",
    pgrating: "+18",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Musical",
    subgenre: ["MUSICAL"],
    thumbnail: null,
    tags: ["Musical"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Music documentary.",
    objecttag: null,
    details: null,
    productionyear: 2024,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 5757,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "4",
    contentprovider: "paramountplus",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "4",
      title: "AsWeSpeak",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/toolbox/paramountplus/mo-portrait-65deda0173fec95dc8daf6ce-203c00.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["GC2WUQO9"]
  },
  {
    objectid: "5",
    objecttype: "CONTENT",
    partnerid: null,
    title: "Persecución Mortal",
    defaulttitle: "Persecución Mortal",
    defaultgenre: "Acción",
    publishtime: "2026-02-21",
    endtime: "2027-05-31",
    shortdescription: "Acción y suspenso.",
    ratingtype: "NUMERIC",
    pgrating: "+16",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Acción",
    subgenre: ["Acción"],
    thumbnail: null,
    tags: ["Acción"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Action thriller.",
    objecttag: null,
    details: null,
    productionyear: 2022,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 5461,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "5",
    contentprovider: "paramountplus",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "5",
      title: "Persecucion",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/toolbox/paramountplus/mo-portrait-675148f473fec95dc8e576af-e09880.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["GC2WUQO9"]
  },
  {
    objectid: "6",
    objecttype: "CONTENT",
    partnerid: null,
    title: "Negocios de Familia",
    defaulttitle: "Negocios de Familia",
    defaultgenre: "DRAMA",
    publishtime: "2026-07-01",
    endtime: "2026-09-30",
    shortdescription: "Drama familiar.",
    ratingtype: "NUMERIC",
    pgrating: "+13",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "DRAMA",
    subgenre: ["CRIME"],
    thumbnail: null,
    tags: ["Drama"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Family drama.",
    objecttag: null,
    details: null,
    productionyear: 1990,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 6835,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "6",
    contentprovider: "CINDIE",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "CINDIE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "6",
      title: "Negocios",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/cindie/mo-dish0000000012395701-dm_20250210_6184_20250210112748-279fabb81c7d7f08.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["23VPUSTI"]
  },
  {
    objectid: "7",
    objecttype: "CONTENT",
    partnerid: null,
    title: "Sommersby",
    defaulttitle: "Sommersby",
    defaultgenre: "DRAMA",
    publishtime: "2025-12-30",
    endtime: "2026-03-31",
    shortdescription: "Drama de época.",
    ratingtype: "NUMERIC",
    pgrating: "+13",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "DRAMA",
    subgenre: ["THRILLER"],
    thumbnail: null,
    tags: ["Drama"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "War romance.",
    objecttag: null,
    details: null,
    productionyear: 1993,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 6807,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "7",
    contentprovider: "CINDIE",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "7",
      title: "Sommersby",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/cindie/mo-dish0000000012711401-dm_20250327_5034_20250327113106-7873ec27c549fc07.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["23VPUSTI"]
  },
  {
    objectid: "8",
    objecttype: "CONTENT",
    partnerid: null,
    title: "ORCA",
    defaulttitle: "ORCA",
    defaultgenre: "DRAMA",
    publishtime: "2025-12-30",
    endtime: "2027-02-03",
    shortdescription: "Romanticismo en la isla.",
    ratingtype: "NUMERIC",
    pgrating: "+13",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "DRAMA",
    subgenre: ["ROMANCE"],
    thumbnail: null,
    tags: ["Drama"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Romantic drama.",
    objecttag: null,
    details: null,
    productionyear: 2020,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "MOVIE",
    subcategory: null,
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    duration: 6326,
    bandorartist: null,
    skip: null,
    playlead: "NO",
    cpcontentid: "8",
    contentprovider: "CINDIE",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "8",
      title: "ORCA",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/cindie/mo-dish0000000012036401-dm_20230314_9703_20230314163128-54437bb3cb60112a.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["23VPUSTI"]
  },
  {
    objectid: "9",
    objecttype: "SERIES",
    partnerid: null,
    title: "Pure: Operación Secreta",
    defaulttitle: "Pure",
    defaultgenre: "DRAMA",
    publishtime: "2025-06-28",
    endtime: "2028-06-27",
    shortdescription: "Serie de espías.",
    ratingtype: "NUMERIC",
    pgrating: "+13",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "DRAMA",
    subgenre: ["ACTION"],
    thumbnail: null,
    tags: ["Drama"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Spy thriller series.",
    objecttag: null,
    details: null,
    productionyear: 2017,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "TVSHOW",
    subcategory: null,
    duration: 30,
    seasoncount: 1,
    totalduration: 15534,
    cpcontentid: "9",
    contentprovider: "CINDIE",
    playbacktype: "STREAMBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "9",
      title: "Pure",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/cindie/sr-cind000412010010-dm_20250627_7944_20250627145002-cac617095b209d95.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["23VPUSTI"],
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    bandorartist: null,
    skip: null
  },
  {
    objectid: "10",
    objecttype: "SERIES",
    partnerid: null,
    title: "Parque Yellowstone",
    defaulttitle: "Yellowstone 150",
    defaultgenre: "Documental",
    publishtime: "2026-02-12",
    endtime: "2027-02-28",
    shortdescription: "Naturaleza y vida silvestre.",
    ratingtype: "NUMERIC",
    pgrating: "+16",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Documental",
    subgenre: ["Documental"],
    thumbnail: null,
    tags: ["Doc"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Nature documentary.",
    objecttag: null,
    details: null,
    productionyear: 2022,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "TVSHOW",
    subcategory: null,
    duration: 30,
    seasoncount: 1,
    totalduration: 10045,
    cpcontentid: "10",
    contentprovider: "paramountplus",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "10",
      title: "Yellowstone",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/toolbox/paramountplus/sr-portrait-6675190c73fec95dc8dee4ca-f8c000.jpeg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["GC2WUQO9"],
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    bandorartist: null,
    skip: null
  },
  {
    objectid: "11",
    objecttype: "SERIES",
    partnerid: null,
    title: "Yellowstone",
    defaulttitle: "Yellowstone Series",
    defaultgenre: "Drama",
    publishtime: "2026-02-24",
    endtime: "2027-05-09",
    shortdescription: "Drama del oeste americano.",
    ratingtype: "NUMERIC",
    pgrating: "+16",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Drama",
    subgenre: ["Drama"],
    thumbnail: null,
    tags: ["Drama"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Western drama series.",
    objecttag: null,
    details: null,
    productionyear: 2018,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "TVSHOW",
    subcategory: null,
    duration: 30,
    seasoncount: 5,
    totalduration: 164975,
    cpcontentid: "11",
    contentprovider: "paramountplus",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "11",
      title: "Yellowstone",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/toolbox/paramountplus/sr-portrait-625f097c149e1cced8b7e1e5-000000.jpeg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["GC2WUQO9"],
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    bandorartist: null,
    skip: null
  },
  {
    objectid: "12",
    objecttype: "SERIES",
    partnerid: null,
    title: "Pequeños Desastres",
    defaulttitle: "Pequeños",
    defaultgenre: "SUSPENSO",
    publishtime: "2026-01-06",
    endtime: "2030-08-16",
    shortdescription: "Serie de suspenso.",
    ratingtype: "NUMERIC",
    pgrating: "+16",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "SUSPENSO",
    subgenre: [],
    thumbnail: null,
    tags: ["Suspenso"],
    contentlanguage: ["ENG"],
    objectowner: null,
    jobid: null,
    longdescription: "Suspense series.",
    objecttag: null,
    details: null,
    productionyear: 2025,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: {},
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "TVSHOW",
    subcategory: null,
    duration: 30,
    seasoncount: 1,
    totalduration: 16837,
    cpcontentid: "12",
    contentprovider: "paramountplus",
    playbacktype: "STREAMBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "12",
      title: "Desastres",
      postertype: "PORTRAIT",
      quality: "HD",
      filelist: [{
        quality: "HD",
        filename: "https://dclkcq4v0w4d8.cloudfront.net/POSTER/mq0duj18kp8_PORTRAIT_HD.jpg",
        format: "jpg"
      }],
      pgrating: "ATP",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "CAROUSEL",
      posterurltype: "CDN"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["GC2WUQO9"],
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    bandorartist: null,
    skip: null
  },
  {
    objectid: "13",
    objecttype: "SERIES",
    partnerid: null,
    title: "Lioness",
    defaulttitle: "Lioness",
    defaultgenre: "Drama",
    publishtime: "2026-02-24",
    endtime: "2034-10-26",
    shortdescription: "Serie de acción y drama.",
    ratingtype: "NUMERIC",
    pgrating: "+18",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Drama",
    subgenre: ["Drama"],
    thumbnail: null,
    tags: ["Drama"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Action drama series.",
    objecttag: null,
    details: null,
    productionyear: 2023,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "TVSHOW",
    subcategory: null,
    duration: 30,
    seasoncount: 2,
    totalduration: 44692,
    cpcontentid: "13",
    contentprovider: "paramountplus",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "13",
      title: "Lioness",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/toolbox/paramountplus/sr-portrait-671dbe4e73fec95dc8e431ce-fab000.jpeg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["GC2WUQO9"],
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    bandorartist: null,
    skip: null
  },
  {
    objectid: "14",
    objecttype: "SERIES",
    partnerid: null,
    title: "Super Shore",
    defaulttitle: "Super Shore",
    defaultgenre: "Reality",
    publishtime: "2026-02-24",
    endtime: "2051-12-31",
    shortdescription: "Reality show emocionante.",
    ratingtype: "NUMERIC",
    pgrating: "+16",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "Reality",
    subgenre: ["Reality"],
    thumbnail: null,
    tags: ["Reality"],
    contentlanguage: [],
    objectowner: null,
    jobid: null,
    longdescription: "Reality entertainment.",
    objecttag: null,
    details: null,
    productionyear: 2016,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: null,
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "TVSHOW",
    subcategory: null,
    duration: 30,
    seasoncount: 3,
    totalduration: 122484,
    cpcontentid: "14",
    contentprovider: "paramountplus",
    playbacktype: "EXTERNALURLBASEDPLAYBACK",
    subcontentprovider: "VLIVE",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "14",
      title: "Super Shore",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/toolbox/paramountplus/sr-portrait-63ff97d9a4cc292e2f50fb43-0081ff.jpeg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["GC2WUQO9"],
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    bandorartist: null,
    skip: null
  },
  {
    objectid: "15",
    objecttype: "SERIES",
    partnerid: null,
    title: "La Voz 2025",
    defaulttitle: "La Voz",
    defaultgenre: "REALITY SHOW",
    publishtime: "2025-09-16",
    endtime: "2028-09-15",
    shortdescription: "Reality show de canto.",
    ratingtype: "NUMERIC",
    pgrating: "+13",
    parentid: null,
    objectstatus: "ACTIVE",
    genre: "REALITY SHOW",
    subgenre: [],
    thumbnail: null,
    tags: ["Reality"],
    contentlanguage: ["ENG"],
    objectowner: null,
    jobid: null,
    longdescription: "Voice competition.",
    objecttag: null,
    details: null,
    productionyear: 2025,
    releasedate: null,
    imdbid: null,
    advisory: null,
    metacontent: {},
    skilllevel: null,
    estimatedtime: null,
    whatwelearn: null,
    category: "TVSHOW",
    subcategory: null,
    duration: 30,
    seasoncount: 1,
    totalduration: 106051,
    cpcontentid: "15",
    contentprovider: "ATRESPLAYER",
    playbacktype: "STREAMBASEDPLAYBACK",
    subcontentprovider: "ATRESPLAYER",
    CONTENTSYNDICATION: true,
    poster: [{
      posterid: "15",
      title: "LaVoz",
      postertype: "PORTRAIT",
      quality: "SD",
      filelist: [{
        quality: "SD",
        filename: "https://dishstorage.akamaized.net/assets/atresplayer/sr-atpl94901000-dm_20251003_2132_20251003215743-d1d17434ad54dae7.jpg",
        format: null
      }],
      pgrating: "G",
      posterlanguage: "ENG",
      postertags: null,
      posterusage: "RAIL",
      posterurltype: "HYPERLINK"
    }],
    resources: [],
    castncrew: { cast: [], crew: [] },
    availabilityset: ["VAAHW0OO"],
    seriesid: null,
    seriesname: null,
    seasonid: null,
    seasonname: null,
    seasonnum: null,
    episodenum: null,
    albumid: null,
    albumname: null,
    track: null,
    bandorartist: null,
    skip: null
  }
];
